### ISSUE TITLE
On mobile device DEM is rotated of 90 degree.

### ISSUE THREAD

**Issue by lucacasagrande** [datadesk/vr-interactives-three-js#7]
Hi,
thanks for this great tutorial!
I tried it on mobile device but DEM is rotated of 90 degree.

**Comment by emamd** [comment]
This was a bug I found in the original Mars project, it looks like the VR controls for some reason reset the quaternion of the camera, overriding the camera.lookAt() command. 

In the Gale crater page, I hacked around this by stashing the quaternion the camera should have like this:

``` javascript
    camera.originalQuaternion = new THREE.Quaternion();
    camera.originalQuaternion.copy(camera.quaternion);
```

And then creating a completely different camera for the VR controls, and in the render loop, applying that to the camera's quaternion:

``` javascript
camera.quaternion.multiplyQuaternions(camera.originalQuaternion, vrCamera.quaternion);
```

This all seemed a little too hefty to bring up in a 60-minute session, so I'm happy for now to gloss over the bug and explain it further if needed.

**Comment by emamd** [comment]
Though if you know another way around it, I'd be really happy to know.
